### ISSUE TITLE
Plugin was not getting activated when WooCommerce was active instead an error was shown.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/currency-per-product-for-woocommerce-lite#11]
Plugin was throwing an error when WooCommerce was active and trying to activate the Currency Per Product plugin.

Error: Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Tried to do the following cases on client site:
1) Deactivate all the plugin except WooCommerce then tried to activate the Currency per Product plugin.
2) All plugins are activated and then tried to activate the Currency per Product plugin.
3) Also tried activating the Currency per product plugin when WooCommerce is deactivated and then tried to activate the WooCommerce plugin then too error exists.

Ticket: https://tychesoftwares.freshdesk.com/a/tickets/8611

**Comment by pinalj** [comment]
Not replicated at our end. Fixed in https://github.com/TycheSoftwares/currency-per-product-for-woocommerce-lite/commit/915bbcaa076a4a1c56cdcf6de88e3b6ed4b5a04b
