### ISSUE TITLE
Make "Update rate" field as read only

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/currency-per-product-for-woocommerce-lite#19]
Make "Update rate" field as read-only filed
In this lite plugin, we are not allowed to set "Enter rate Automatically
 
https://www.screencast.com/t/dxmrkyhx19

**Comment by Shasvat7** [comment]
This has been solved in this commit:-https://github.com/TycheSoftwares/currency-per-product-for-woocommerce-lite/pull/32/commits/0232b1df8c046f0ed988cf58b4860a2a06b93e32
