### ISSUE TITLE
Currency is not displayed for the selected categories product when 'Currency per product categories' setting is enabled.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/currency-per-product-for-woocommerce-lite#20]
Other Currency is not displayed on the front end for the selected product category in the 'Product categories' dropdown of the 'Currency # 1' setting.

Attaching video of the settings: https://drive.google.com/a/tychesoftwares.com/file/d/11SJ3GYD21KVPHrnXWJN1jfG03AQjNHkG/view?usp=drivesdk

Front end: https://drive.google.com/a/tychesoftwares.com/file/d/1r6COXrwHWzOvLq5OEuqMqVx9EnY1GU5F/view?usp=drivesdk

set up screenshort : https://www.screencast.com/t/H8B0lgBdaUj8
https://www.screencast.com/t/k9dhTWHT8
https://www.screencast.com/t/YTbDycz0
https://www.screencast.com/t/mcvsi4UTym12

Edit product set up: https://www.screencast.com/t/XzNvxMkSe

Note : The same issue present in the pro version
https://github.com/TycheSoftwares/currency-per-product-for-woocommerce-pro/issues/2

**Comment by Shasvat7** [comment]
This issue has been fixed in this commit:-https://github.com/TycheSoftwares/currency-per-product-for-woocommerce-lite/pull/30/commits/0b1f92bb7bd9e813aaf00b815e077b95fa4db58a
