### ISSUE TITLE
"Update server" field should be read only field in lite version

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/currency-per-product-for-woocommerce-lite#21]
"Update server" field should be read-only field in the lite version

As this field is work with Enter rate automatically, Lite version we dont have that option
so put this field as read-only field

https://www.screencast.com/t/pjxZV5GBk4

**Comment by Shasvat7** [comment]
This has been solved in this commit:-https://github.com/TycheSoftwares/currency-per-product-for-woocommerce-lite/commit/62d0d521168f81c7195fb5b8a3b7f405c5285ca4
