### ISSUE TITLE
Price Filter for the product is not working properly

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/currency-per-product-for-woocommerce-lite#31]
When we filter the price on the shop page it is getting filtered based on the price which is set on the backend.
Suppose the product price is 655 in USD and on the shop page the price is converted in 3.210 TRY so by filtering the price in range 140-700, it shows that product considering 655 USD as the price and not with TRY price
So, while filtering for 140-700 TRY to range the product with a 3.210 TRY price should not come up means the converted price.

Ticket Link: https://tychesoftwares.freshdesk.com/a/tickets/15369

**Comment by Shasvat7** [comment]
This issue has been fixed in this  commit:-https://github.com/TycheSoftwares/currency-per-product-for-woocommerce-lite/pull/33/commits/28ea4482df2d7a3441b7d4c7a34131a95c346d89
